version: '3'
services:
  app:
    build: ./
    ports:
      - "5000:5000"
    volumes:
      - type: bind
        target: /template
        source: C:\Pro\Cours\A5 - IPP\Data Stream Processing\TP\TP3\template
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: users
      MYSQL_USER: mayo
      MYSQL_PASSWORD: mayo
      MYSQL_HOST: mysql
    ports:
      - "3306:3306"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./data:/var/lib/mysql